openapi: 3.0.0
info:
    title: Jobs API
    contact: {}
    version: '1.0'
servers:
    - url: http://localhost:5000/api/v1/
      description: dev
      variables: {}
paths:
    /auth/login:
        post:
            tags:
                - Auth
            summary: Login User
            operationId: LoginUser
            parameters: []
            requestBody:
                description: ''
                content:
                    application/json:
                        schema:
                            allOf:
                                - $ref: '#/components/schemas/LoginUserRequest'
                                - example:
                                      email: geo@gmail.com
                                      password: secret
                        example:
                            email: geo@gmail.com
                            password: secret
                required: true
            responses:
                '200':
                    description: ''
                    headers: {}
            deprecated: false
            security: []
    /auth/register:
        post:
            tags:
                - Auth
            summary: Register User
            operationId: RegisterUser
            parameters: []
            requestBody:
                description: ''
                content:
                    application/json:
                        schema:
                            allOf:
                                - $ref: '#/components/schemas/RegisterUserRequest'
                                - example:
                                      name: Peter
                                      email: peter@gmail.com
                                      password: myPeter
                        example:
                            name: Peter
                            email: peter@gmail.com
                            password: myPeter
                required: true
            responses:
                '200':
                    description: ''
                    headers: {}
            deprecated: false
            security: []
    /jobs:
        post:
            tags:
                - Jobs
            summary: Create Job
            operationId: CreateJob
            parameters: []
            requestBody:
                description: ''
                content:
                    application/json:
                        schema:
                            allOf:
                                - $ref: '#/components/schemas/CreateJobRequest'
                                - example:
                                      company: netflix
                                      position: back-end dev
                        example:
                            company: netflix
                            position: back-end dev
                required: true
            responses:
                '200':
                    description: ''
                    headers: {}
            deprecated: false
            security:
                - bearer: []
        get:
            tags:
                - Jobs
            summary: Get All Jobs
            operationId: GetAllJobs
            parameters: []
            responses:
                '200':
                    description: ''
                    headers: {}
            deprecated: false
            security:
                - bearer: []
    /jobs/{id}:
        parameters:
            - in: path
              name: id
              schema:
                  type: string
              required: true
              description: the job id
        get:
            tags:
                - Jobs
            summary: Get One Job
            operationId: GetOneJob
            parameters: []
            responses:
                '200':
                    description: ''
                    headers: {}
            deprecated: false
            security:
                - bearer: []
        delete:
            tags:
                - Jobs
            summary: Get One Job Copy
            operationId: GetOneJobCopy
            parameters: []
            responses:
                '200':
                    description: ''
                    headers: {}
            deprecated: false
            security:
                - bearer: []

        patch:
            tags:
                - Jobs
            summary: Update Job
            operationId: UpdateJob
            parameters: []
            requestBody:
                description: ''
                content:
                    application/json:
                        schema:
                            allOf:
                                - $ref: '#/components/schemas/UpdateJobRequest'
                                - example:
                                      company: Uber
                                      status: interview
                                      position: tester
                        example:
                            company: Uber
                            status: interview
                            position: tester
                required: true
            responses:
                '200':
                    description: ''
                    headers: {}
            deprecated: false
            security:
                - bearer: []
components:
    schemas:
        LoginUserRequest:
            title: LoginUserRequest
            required:
                - email
                - password
            type: object
            properties:
                email:
                    type: string
                password:
                    type: string
            example:
                email: geo@gmail.com
                password: secret
        RegisterUserRequest:
            title: RegisterUserRequest
            required:
                - name
                - email
                - password
            type: object
            properties:
                name:
                    type: string
                email:
                    type: string
                password:
                    type: string
            example:
                name: Peter
                email: peter@gmail.com
                password: myPeter
        CreateJobRequest:
            title: CreateJobRequest
            required:
                - company
                - position
            type: object
            properties:
                company:
                    type: string
                position:
                    type: string
            example:
                company: netflix
                position: back-end dev
        UpdateJobRequest:
            title: UpdateJobRequest
            required:
                - company
                - status
                - position
            type: object
            properties:
                company:
                    type: string
                status:
                    type: string
                position:
                    type: string
            example:
                company: Uber
                status: interview
                position: tester
    securitySchemes:
        bearer:
            type: http
            scheme: bearer
security: []
tags:
    - name: Auth
      description: ''
    - name: Jobs
      description: ''
