### !This relies on REST-CLIENT vscode extension
@baseUrl = http://localhost:3000
@id = 2
@accessToken = 'this is a test'

### Get Request
GET {{baseUrl}}/coffees
Authorization: Bearer {{accessToken}}

### Get Request with limit
GET {{baseUrl}}/coffees?limit=1

### Get Request with offset
GET {{baseUrl}}/coffees?offset=1

### Get Request
GET {{baseUrl}}/coffees/{{id}}

### Post Request
POST {{baseUrl}}/coffees
Content-Type: application/json

{
  "name": "Coffee #5",
  "brand": "TT",
  "flavors": ["moi"]
}

###  PATCH
PATCH {{baseUrl}}/coffees/2
Content-Type: application/json

{
	"name": "Coffee #2"
}